export const USER_TOKEN= 'USER_TOKEN'
export const USER_ISLOGINED= 'USER_ISLOGINED'
export const USER_UINFO= 'USER_UINFO'

export const SUB_NORMAL_AUTO_REQUEST = 'SUB_NORMAL_AUTO_REQUEST'

export const SET_POST_JUDGE_DATA = 'SET_POST_JUDGE_DATA'
export const SET_PRE_PROBLEM_PATH = 'SET_PRE_PROBLEM_PATH'
